baseURL = "https://wat.io/"
languageCode = "en-us"
title = "วัด [wát]"
theme = "ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
subtitle = "a place for contemplation"
featherIconsCDN = true

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/jasonkeene"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/jasonkeene"
